
package Ventanas;

import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import proyecto1.Datos;
import proyecto1.Datosenvios;
import proyecto1.Envios;
import proyecto1.Facturacion;
import proyecto1.Infcompra;
import proyecto1.Preciomod;
import proyecto1.Precios;
import proyecto1.Regiones;
import proyecto1.RegistroTarjetas;
import proyecto1.Usuarios;


public class InterfazUsuario extends javax.swing.JFrame {
    
    
    public Precios PreciosReg = proyecto1.Proyecto1.PreciosReg;
    public Regiones datosregiones = proyecto1.Proyecto1.datosreg;
    public RegistroTarjetas regtarjetas = proyecto1.Proyecto1.regtarjeta;
    public Facturacion facturacion = proyecto1.Proyecto1.facturacion;
    public Envios envios = proyecto1.Proyecto1.envios;
    public Usuarios usuarios = proyecto1.Proyecto1.usuarios;
    
    DefaultListModel listatarjetas = new DefaultListModel();
    DefaultListModel listafac = new DefaultListModel();
    DefaultListModel Datoscotizados = new DefaultListModel();
    DefaultListModel envhechos = new DefaultListModel();
    DefaultListModel informacion = new DefaultListModel();
    
    private Compra Compra ;
    
    public InterfazUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TarjetasRegistradas = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreTarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NumeroTarjeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FechaVencimiento = new javax.swing.JTextField();
        Tarjeta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatosFacturacion = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NombreF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DireccionF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nit = new javax.swing.JTextField();
        Facturacion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Nopaquetes = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Peso = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TipoEnvio = new javax.swing.JComboBox<>();
        Cotizar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Envio = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        opcionpago = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 4), new java.awt.Dimension(0, 4), new java.awt.Dimension(32767, 4));
        Departamentos1 = new javax.swing.JComboBox<>();
        Departamentos2 = new javax.swing.JComboBox<>();
        municipio1 = new javax.swing.JComboBox<>();
        municipio2 = new javax.swing.JComboBox<>();
        mostrartotal = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inforigen = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        inforegion = new javax.swing.JLabel();
        infopaquetes = new javax.swing.JLabel();
        inforecargo = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Factura = new javax.swing.JButton();
        Guia = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        SelecEnvios = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        mostrarorigen = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        mostrardestino = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        mostrarfacturacion = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        mostrarservicio = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Tarjetas");

        jLabel2.setText("Tarjetas Registradas ");

        jScrollPane1.setViewportView(TarjetasRegistradas);

        jLabel3.setText("Registrar nueva tarjeta");

        jLabel4.setText("Nombre de la Tarjeta");

        jLabel5.setText("Numero de Tarjeta");

        jLabel6.setText("Fecha de Vencimiento");

        Tarjeta.setText("Registrar Tarjeta");
        Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Datos de Facturacion");

        jScrollPane2.setViewportView(DatosFacturacion);

        jLabel8.setText("Agregar  Datos de Facturacion");

        jLabel9.setText("Nombre");

        jLabel10.setText("Direccion");

        jLabel11.setText("NIT");

        Facturacion.setText("Agregar Datos");
        Facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturacionActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel32.setText("DD-MM-AAAA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel32))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(NumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(FechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Tarjeta))
                                        .addComponent(NombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreF)
                                    .addComponent(DireccionF)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(Facturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(84, 84, 84))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(NumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tarjeta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(DireccionF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Facturacion))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos de Compra", jPanel1);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Direccion de Origen");

        jLabel13.setText("Municipio");

        jLabel14.setText("Departamento");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Direccion de Destino");

        jLabel16.setText("Municipio");

        jLabel17.setText("Departamento");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Numero de paquetes ");

        Nopaquetes.setText("0");
        Nopaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NopaquetesActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Peso del paquete");

        Peso.setText("0");
        Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Tipo de envio");

        TipoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar", "Especial" }));

        Cotizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cotizar.setText("Cotizar");
        Cotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotizarActionPerformed(evt);
            }
        });

        jLabel21.setText("Datos");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Precio Total");

        Envio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Envio.setText("Realizar Envio");
        Envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvioActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Opcion de pago");

        opcionpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Origen", "Pago contra entrega" }));

        Departamentos1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Departamentos1ItemStateChanged(evt);
            }
        });

        Departamentos2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Departamentos2ItemStateChanged(evt);
            }
        });

        mostrartotal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mostrartotal.setText("00");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel30.setText("Q");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel34.setText("Envio por region");

        jLabel35.setText("Q");

        jLabel36.setText("Precio de paquetes");

        jLabel37.setText("Q");

        jLabel38.setText("Recargo por opcion de pago");

        inforegion.setText("00");

        infopaquetes.setText("00");

        inforecargo.setText("00");

        jLabel42.setText("Q");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inforigen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel38)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inforegion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addComponent(infopaquetes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inforecargo)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(inforigen))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(inforegion))
                .addGap(36, 36, 36)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(infopaquetes))
                .addGap(32, 32, 32)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inforecargo)
                    .addComponent(jLabel42))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel33.setText("(Peso en lbs)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(opcionpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(mostrartotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Departamentos2, javax.swing.GroupLayout.Alignment.LEADING, 0, 229, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel33))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Departamentos1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Peso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(municipio2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nopaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18)))))
                            .addComponent(TipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(364, 364, 364)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(369, 369, 369))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Departamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel15)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Departamentos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(municipio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nopaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel20))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TipoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(4, 4, 4)))
                .addComponent(jLabel23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mostrartotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcionpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Cotizacion de Paquetes", jPanel3);

        Factura.setText("Descargar Factura");
        Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaActionPerformed(evt);
            }
        });

        Guia.setText("Descargar Guia");
        Guia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuiaActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Envios Solicitados ");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Estado de envio");

        jLabel26.setText("Informacion");

        jLabel28.setText("Descargar Archivos");

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        SelecEnvios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelecEnviosItemStateChanged(evt);
            }
        });

        jLabel29.setText("Seleccionar Envio");

        jLabel27.setText("pendiente de recoleccion");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel39.setText("Direccion Origen:");

        mostrarorigen.setText("\"\"");

        jLabel41.setText("Direccion Destino");

        mostrardestino.setText("\"\"");

        jLabel44.setText("Datos de Facturacion");

        mostrarfacturacion.setText("\"\"");

        jLabel46.setText("Tipo de Servicio:");

        mostrarservicio.setText("\"\"");

        jLabel48.setText("Total Pagado :");

        jLabel49.setText("00");

        jLabel50.setText("Q");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mostrarorigen)
                            .addComponent(jLabel39)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(mostrardestino)
                                    .addGap(31, 31, 31))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel50)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel49))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mostrarservicio)
                                        .addComponent(mostrarfacturacion))
                                    .addGap(30, 30, 30)))
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel46))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarorigen)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrardestino)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarfacturacion)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarservicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(Actualizar)
                                    .addComponent(jLabel29)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(SelecEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(184, 184, 184)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel28))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Guia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel31)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGap(132, 132, 132)
                        .addComponent(jLabel28)
                        .addGap(55, 55, 55)
                        .addComponent(Guia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Actualizar)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(SelecEnvios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Envios Solicitados", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void listatarjetas(){
        TarjetasRegistradas.setModel(listatarjetas);
       listatarjetas.clear();
        
        ArrayList <Infcompra> tarjetas = new ArrayList<Infcompra>();
        tarjetas = regtarjetas.getRegtarjetas();
        
        for(int i =0; i< tarjetas.size();i++) {
            
            String numero = tarjetas.get(i).getDato2();
            char a = numero.charAt(14);
            char b = numero.charAt(13);
            char c = numero.charAt(12);
            char d = numero.charAt(11);
            String oculto = "----------" + d + c + b+ a;
            String agregar =  tarjetas.get(i).getDato1() 
                 + " / " + oculto + " / " 
                    + tarjetas.get(i).getDato3();
            
         listatarjetas.addElement(agregar);
        listatarjetas.addElement("          ");
        } 
    
    }
    

     public void listafacturacion(){
        DatosFacturacion.setModel(listafac);
       listafac.clear();
        
        ArrayList <Infcompra> facturacion = new ArrayList<Infcompra>();
        facturacion = this.facturacion.getFacturacion();
        
        for(int i =0; i< facturacion.size();i++) {
            
            String agregar =   facturacion.get(i).getDato1() 
                 + " / " + facturacion.get(i).getDato2()+ " / " 
                    + facturacion.get(i).getDato3();
            
         listafac.addElement(agregar);
         listafac.addElement("          ");
        } 
    
    }
     
     
      public void deptosreg(){
           this.Departamentos1.removeAllItems();
           this.Departamentos2.removeAllItems();
          
        Set <Datos> d = new HashSet<Datos>();
        d=  datosregiones.getDeptosreg();   
        
        
          for (Datos datos : d) {
             Departamentos1.addItem(datos.getDato3()) ;
             Departamentos2.addItem(datos.getDato3()) ;
          }
 
      }
  
    
    private void TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaActionPerformed


        String Nomtarjeta = this.NombreTarjeta.getText();
        String Numtarjeta = this.NumeroTarjeta.getText();
        String FechaVen = this.FechaVencimiento.getText();
        String nombre = usuarios.getUsuarioactual();
        
        if(Numtarjeta.length() < 15 || Numtarjeta.length() > 15 ) {
            JOptionPane.showMessageDialog(rootPane, "Numero de tarjeta incorrecto, se requieren 15 digitos");
        
        } else {
        
            Infcompra datos = new Infcompra (nombre,Nomtarjeta,Numtarjeta,FechaVen);
        regtarjetas.agregardatos(datos);
        
        listatarjetas();
        
        }
   
        
        
    }//GEN-LAST:event_TarjetaActionPerformed

    private void EnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvioActionPerformed
          
          double peso = getpeso();
          double cant = getcant();
          
          if (peso==0 && cant ==0 ){
          JOptionPane.showMessageDialog(null, "Complete todos los datos de cotizacion");
          }else{
          Compra = new Compra();
         Compra.setVisible(true); 
         datosregiones.contador(buscarregion(departamento()));
         
          }
         
    }//GEN-LAST:event_EnvioActionPerformed

    private void FacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturacionActionPerformed
        
        String Nomfacturacion = this.NombreF.getText();
        String Direccion = this.DireccionF.getText();
        String nit = this.nit.getText();
        String nombre = usuarios.getUsuarioactual();
        
        if(Nomfacturacion.length()==0 || Direccion.length() == 0 || nit.length()==0){
        JOptionPane.showMessageDialog(null, "Complete todos los datos de Facturacion");
        }else{
        Infcompra datos = new Infcompra (nombre,Nomfacturacion,Direccion,nit);
        facturacion.agregardatos(datos);
        listafacturacion();
        }
        
        
        
    }//GEN-LAST:event_FacturacionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        deptosreg();
//        informacionenvio();
    }//GEN-LAST:event_formWindowOpened

    private void Departamentos1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Departamentos1ItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED){
           String depto = this.Departamentos1.getSelectedItem().toString();
          String [] d = new String [datosregiones.buscarmun(depto).size()];
          
             for (int i = 0; i <  datosregiones.buscarmun(depto).size() ; i++) {
              
                 d [i]= datosregiones.buscarmun(depto).get(i);
             }
 
           
             this.municipio1.setModel(new DefaultComboBoxModel(d));
 
      }
    }//GEN-LAST:event_Departamentos1ItemStateChanged

    private void CotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotizarActionPerformed
  
        
        int s = this.Departamentos1.getItemCount();
        int t = this.Departamentos1.getItemCount();
        int u = this.Departamentos1.getItemCount();
        int v = this.Departamentos1.getItemCount();
        
        if(s == 0 ||
                t == 0|| 
                u== 0 || 
                v ==0 ){
        JOptionPane.showMessageDialog(rootPane, "El administrador no ha ingresado datos de direcciones");
        }else{
        
        
        Datoscotizados.addElement(mostrardatos());   

        inforegion.setText(Double.toString(calcularservicio()));
        infopaquetes.setText(Double.toString(getpeso()*getcant()));
        String recargo = "0";
        String opcionpag = this.opcionpago.getSelectedItem().toString();
            if(opcionpag.equalsIgnoreCase("Pago contra entrega")){
             recargo = "5";
        
        inforecargo.setText(recargo);

        }
        mostrartotal.setText(Double.toString(preciototal()));   
        }
    }//GEN-LAST:event_CotizarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
         informacionenvio();
    }//GEN-LAST:event_ActualizarActionPerformed

    private void SelecEnviosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelecEnviosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
        
           ArrayList<Datosenvios> info = new ArrayList<Datosenvios>();    
           
           info = envios.seleccionarinf(usuarios.getUsuarioactual()); 
           System.out.println(info.get(1).getCodigopaquete());
           
           Datosenvios Encontrado = null;
       for (Datosenvios d : info) {
           if(d.getCodigopaquete().equalsIgnoreCase(this.SelecEnvios.getSelectedItem().toString())) {
           Encontrado = d;
           
           }
       }
            System.out.println(Encontrado);
            
          this.mostrarorigen.setText(Encontrado.getOrigen());
          this.mostrardestino.setText(Encontrado.getDestino());
          this.mostrarfacturacion.setText(Encontrado.getDatosFac());
          this.mostrarservicio.setText(Encontrado.getServicio());
          this.mostrartotal.setText(Encontrado.getTotal());
           //Info.setModel(informacion);
          //informacion.addElement(Encontrado);
            
      }
    }//GEN-LAST:event_SelecEnviosItemStateChanged

    private void GuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuiaActionPerformed
        String ruta = "C:\\Users\\joz\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto1\\Guia.html";
        String codigo = this.SelecEnvios.getSelectedItem().toString();
        JFileChooser seleccionarCarpeta = new JFileChooser();
        seleccionarCarpeta.setCurrentDirectory(new File("."));
        seleccionarCarpeta.setDialogTitle("Seleccione la carpeta de Descarga");
        seleccionarCarpeta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
 seleccionarCarpeta.setAcceptAllFileFilterUsed(false);
 
        if(seleccionarCarpeta.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            ruta = seleccionarCarpeta.getSelectedFile().getPath();
            ruta = ruta+"\\Guia.html";
            envios.setRuta1(ruta);
            envios.descargarguia(codigo);
        }
       // envios.descargarguia(codigo);
       
    }//GEN-LAST:event_GuiaActionPerformed

    private void FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaActionPerformed
        String ruta = "C:\\Users\\joz\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto1\\Factura.html";
        String codigo = this.SelecEnvios.getSelectedItem().toString();
        JFileChooser seleccionarCarpeta = new JFileChooser();
        seleccionarCarpeta.setCurrentDirectory(new File("."));
        seleccionarCarpeta.setDialogTitle("Seleccione la carpeta de Descarga");
        seleccionarCarpeta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
 seleccionarCarpeta.setAcceptAllFileFilterUsed(false);
 
        if(seleccionarCarpeta.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            ruta = seleccionarCarpeta.getSelectedFile().getPath();
            ruta = ruta+"\\Factura.html";
            envios.setRuta(ruta);  
            envios.descargarfactura(codigo);
        }
  
    }//GEN-LAST:event_FacturaActionPerformed

    private void Departamentos2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Departamentos2ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
         
           String depto = this.Departamentos2.getSelectedItem().toString();
          String [] d = new String [datosregiones.buscarmun(depto).size()];
          
             for (int i = 0; i <  datosregiones.buscarmun(depto).size() ; i++) {
              
                 d [i]= datosregiones.buscarmun(depto).get(i);
             }

             this.municipio2.setModel(new DefaultComboBoxModel(d));
          
        }
    }//GEN-LAST:event_Departamentos2ItemStateChanged

    private void NopaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NopaquetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NopaquetesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        deptosreg();
        informacionenvio();
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Datosenvios> info = new ArrayList<Datosenvios>();    
           
           info = envios.seleccionarinf(usuarios.getUsuarioactual()); 
           System.out.println(info.get(1).getCodigopaquete());
           
           Datosenvios Encontrado = null;
       for (Datosenvios d : info) {
           if(d.getCodigopaquete().equalsIgnoreCase(this.SelecEnvios.getSelectedItem().toString())) {
           Encontrado = d;
           
           }
       }
            System.out.println(Encontrado);
            
          this.mostrarorigen.setText(Encontrado.getOrigen());
          this.mostrardestino.setText(Encontrado.getDestino());
          this.mostrarfacturacion.setText(Encontrado.getDatosFac());
          this.mostrarservicio.setText(Encontrado.getServicio());
          this.mostrartotal.setText(Encontrado.getTotal());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoActionPerformed
        
       public String buscarregion(String depto){
     String region = "";
        Set <Datos> d = new HashSet<Datos>();
        d = datosregiones.getDeptosreg();
     for (Datos datos : d) {
            if (datos.getDato3().equalsIgnoreCase(depto)){
            region = datos.getDato1();
            break;
            }
        }
        
     return region;
    
       }
    
    
        private double calcularservicio(){
         ArrayList <Preciomod> Precios = new ArrayList<Preciomod>();
        Precios=PreciosReg.getPrecios();
    
        String reg = buscarregion(departamento());
 
        double precioEncontrado = 0;
        int i = 0;

      if (reg.equalsIgnoreCase("Metropolitana")) {
      i= 0;
    } else if (reg.equalsIgnoreCase("Norte")) {
     i= 1;
    }else if (reg.equalsIgnoreCase("Nororiente")) {
     i= 2;
    }else if (reg.equalsIgnoreCase("Suroriente")) {
     i= 3;
    }else if (reg.equalsIgnoreCase("Suroccidente")) {
     i= 4;
    }else if (reg.equalsIgnoreCase("Noroccidente")) {
     i= 5;
    }

        if(servicio().equalsIgnoreCase("Estandar")){
      precioEncontrado =  Double.parseDouble(Precios.get(i).getPestandar());
    }else{
    
    precioEncontrado =  Double.parseDouble(Precios.get(i).getPespecial());
    }  
            
        return   precioEncontrado;  
      
        }
    
    
        public String mostrardatos(){
        String datos = "\nDireccion de origen: " + dirorigen()+ 
                       "\nDireccion de entrega: " + direntrega() +
                       "\npeso del producto: " + getpeso()+
                       "\nCantidad de productos: " + getcant()+
                       "\nServicio: " + servicio() ; 
        return datos;
        
        }
    
        public String dirorigen(){
        String dirorigen = this.municipio1.getSelectedItem().toString() + "/"
                + this.Departamentos1.getSelectedItem().toString() ;
        return dirorigen;
        }
         
        
         public String direntrega(){
          String direntrega = this.municipio2.getSelectedItem().toString() + "/"
                + this.Departamentos2.getSelectedItem().toString();
         return direntrega;
         }
        

        public double preciototal(){
        /*
        Total de servicio = Precio de Región Destino (estándar o especial) * Tamaño de
        paquete * número de paquetes
        */  double pregion= calcularservicio();
            double total = pregion*getpeso()*getcant();
            double recargo = 0;
            String opcionpag = this.opcionpago.getSelectedItem().toString();
            if(opcionpag.equalsIgnoreCase("Pago contra entrega")){
             recargo = 5;
            }else{}
            total += recargo;
            return total;
        }
     
        private String departamento(){
        String dir = this.Departamentos2.getSelectedItem().toString();
        return dir;
        }
        
        
        
        public String servicio(){
        String envio = this.TipoEnvio.getSelectedItem().toString();
        return envio;
        }

        public double getpeso(){
        double peso = Double. parseDouble(this.Peso.getText().toString());
        return peso;
        }
    
       public double getcant(){
        double paquete = Double. parseDouble(this.Nopaquetes.getText().toString());
        return paquete;
       }
       
       
       private void informacionenvio(){
       
           ArrayList<Datosenvios> informacion = new ArrayList<Datosenvios>();    
           
       informacion = envios.seleccionarinf(usuarios.getUsuarioactual());
       /*
       for (int i=0; i< informacion.size();i++){
       SelecEnvios.addItem(informacion.get(i).toString());
           */
       
  
          String [] d = new String [informacion.size()];
          
             for (int i = 0; i <  informacion.size() ; i++) {
              
                 d [i]= informacion.get(i).getCodigopaquete();
             }
 
           
             this.SelecEnvios.setModel(new DefaultComboBoxModel(d));
 
  
       }
       
       
       
       private void informacion(){
       
       ArrayList<Datosenvios> informacion = new ArrayList<Datosenvios>();    
           
       informacion = envios.seleccionarinf(usuarios.getUsuarioactual());
       
       for (int i=0; i< informacion.size();i++){
       SelecEnvios.addItem(informacion.get(i).toString());
      
       }
       }
       
       
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Cotizar;
    private javax.swing.JList<String> DatosFacturacion;
    private javax.swing.JComboBox<String> Departamentos1;
    private javax.swing.JComboBox<String> Departamentos2;
    private javax.swing.JTextField DireccionF;
    private javax.swing.JButton Envio;
    private javax.swing.JButton Factura;
    private javax.swing.JButton Facturacion;
    private javax.swing.JTextField FechaVencimiento;
    private javax.swing.JButton Guia;
    private javax.swing.JTextField NombreF;
    private javax.swing.JTextField NombreTarjeta;
    private javax.swing.JTextField Nopaquetes;
    private javax.swing.JTextField NumeroTarjeta;
    private javax.swing.JTextField Peso;
    private javax.swing.JComboBox<String> SelecEnvios;
    private javax.swing.JButton Tarjeta;
    private javax.swing.JList<String> TarjetasRegistradas;
    private javax.swing.JComboBox<String> TipoEnvio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel infopaquetes;
    private javax.swing.JLabel inforecargo;
    private javax.swing.JLabel inforegion;
    private javax.swing.JLabel inforigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mostrardestino;
    private javax.swing.JLabel mostrarfacturacion;
    private javax.swing.JLabel mostrarorigen;
    private javax.swing.JLabel mostrarservicio;
    private javax.swing.JLabel mostrartotal;
    private javax.swing.JComboBox<String> municipio1;
    private javax.swing.JComboBox<String> municipio2;
    private javax.swing.JTextField nit;
    private javax.swing.JComboBox<String> opcionpago;
    // End of variables declaration//GEN-END:variables
}
